Feat/product endpoints
raphdoo/africommerce-saas pull request #10
Opened 2022-10-16 16:56 UTC by tobisupreme

This pull request is a work in progress

The controllers for `createProduct` and `updateProduct` are "finished".
My colleague has "completed" the code for `getProductById` and `deleteProduct`. (They will be opening pull requests to that regard)

I am currently in the process of writing the code for `getAllProducts`.

Pending when subsequent commits are ready, we are open to reviews, feedback, comments, etc 🙏

2022-10-16 16:59 UTC, tobisupreme commented
#4

2022-10-16 19:04 UTC, Skywonda requested changes, later dismissed
do some validations and then write the put the router in the router file

2022-10-16 19:04 UTC, Skywonda commented on products/productController.js
> +    const productToSave = new productModel({
make basic validations on the data types you are collecting before saving them to the database

2022-10-16 19:04 UTC, Skywonda commented on products/productController.js
> +const updateProduct = async (req, res, next) => {
add this routers into the route files

2022-10-17 10:09 UTC, tobisupreme commented
Hi boss! I resolved some conflicts and updated this pull request 🙏

2022-10-17 10:12 UTC, merged